// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  awards: dynamic(() => import("./Awards")),
  contacts: dynamic(() => import("./Contacts")),
  hero: dynamic(() => import("./Hero")),
  works: dynamic(() => import("./Works")),
};
